# Generated by Django 4.1.3 on 2022-11-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='nb_appr_par_nome',
            field=models.IntegerField(default=0),
        ),
    ]
