# Generated by Django 4.1.3 on 2022-11-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_brief_nb_appr_par_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apprenant',
            old_name='nom',
            new_name='nom_apprenant',
        ),
        migrations.RenameField(
            model_name='apprenant',
            old_name='prenom',
            new_name='prenom_apprenant',
        ),
        migrations.RenameField(
            model_name='brief',
            old_name='titre',
            new_name='titre_brief',
        ),
        migrations.RenameField(
            model_name='brief',
            old_name='url',
            new_name='url_brief',
        ),
    ]
