# Generated by Django 4.1.3 on 2022-11-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_nom_apprenant_nom_apprenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='nb_appr_par_nome',
            field=models.IntegerField(default=2),
        ),
    ]
